//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vvctiger.com_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordPair
    {
        public int Pair_Id { get; set; }
        public string Word_1 { get; set; }
        public string Word_2 { get; set; }
        public Nullable<int> Length { get; set; }
        public string Encoding { get; set; }
        public Nullable<System.DateTime> Updated_Timestamp { get; set; }
    }
}
